package mocktls

import (
	"crypto/x509/pkix"
	"fmt"
	"strconv"
	"strings"
)

// PKIXExtensionsToGoStructs converts pkix.Extension (e.g., X509v3 Extended
// Key Usage) into Go data structure strings. This is useful for creating
// extensions from a X.509 certificate not generated by Go.
func PKIXExtensionsToGoStructs(extensions ...pkix.Extension) string {
	builder := strings.Builder{}

	for i, ext := range extensions {
		builder.WriteString(`{
	Id:       []int{`)
		for j, oidInt := range ext.Id {
			builder.WriteString(strconv.Itoa(oidInt))
			if j != len(ext.Id)-1 {
				builder.WriteString(", ")
			}
		}
		builder.WriteString(`},
	Value:    []byte{`)
		for j, val := range ext.Value {
			builder.WriteString(fmt.Sprintf("0x%02X", val))
			if j != len(ext.Value)-1 {
				builder.WriteString(", ")
			}
		}
		builder.WriteString(`},
	Critical: `)
		builder.WriteString(strconv.FormatBool(ext.Critical))
		builder.WriteString(`,
},`)
		if i != len(extensions)-1 {
			builder.WriteString("\n")
		}
	}

	return builder.String()
}
